// error line: 9

Main (->)
    def a <- Foo
end

Foo (-> Int)
    Print "1"
    return 2
    Print "3"
    4
end
